// lib/config/keywords.ts

import { Category } from '@/lib/types';

export const CATEGORY_KEYWORDS: Record<Category, string[]> = {
  'ai-tech': [
    'LLM',
    'GPT',
    'Transformer',
    'BERT',
    '深度学习',
    '神经网络',
    '机器学习',
    'NLP',
    'natural language',
    '训练',
    '推理',
    'fine-tuning',
    '预训练',
    'language model',
    'deep learning',
    'neural network',
    'machine learning',
    'classification',
    'regression',
    'embedding',
    'attention',
    'backpropagation',
    'optimization',
    'gradient',
    'loss function',
  ],
  'agent-tech': [
    'Agent',
    '智能体',
    '多智能体',
    'multi-agent',
    '具身智能',
    'embodied',
    'RAG',
    'retrieval augmented',
    '工具调用',
    'tool use',
    '规划',
    'planning',
    '自主决策',
    'autonomous',
    'CoT',
    'chain of thought',
    'reasoning',
    'decision making',
    'task decomposition',
    'workflow',
    'automation',
    'orchestration',
    'action',
    'environment',
    'perception',
  ],
  'graphics-tech': [
    '渲染',
    'rendering',
    'GPU',
    'CUDA',
    '图形算法',
    'graphics algorithm',
    'shader',
    '光线追踪',
    'ray tracing',
    '三维重建',
    '3D reconstruction',
    'NeRF',
    '视觉计算',
    'visual computing',
    'visualization',
    '计算机图形',
    'computer graphics',
    '图像处理',
    'image processing',
    'texture',
    'mesh',
    'geometry',
    'voxel',
    'photorealistic',
    'splatting',
  ],
};

// 获取所有关键词（用于初步筛选）
export const ALL_KEYWORDS = Object.values(CATEGORY_KEYWORDS).flat();
